"""Decomposition of an estimated source into true / target / interference / artifact.

Transcribed from MATLAB PEASS v2.0.1.

The primary API, `extractDistortionComponents`, takes and returns arrays; the
MATLAB entry point reads and writes `.wav` files, and that is provided as the
thin wrapper `extractDistortionComponents_files`.
"""
MATLAB_SOURCE = "extractDistortionComponents.m"

import os
import sys
import tempfile

import numpy as np
import scipy.io.wavfile

from ._matlab_runtime import hann_periodic
from ._matlab_runtime import matlab_round
from ._matlab_runtime import mstruct_get
from .extractTSIA import extractTSIA
from .myPemoAnalysisFilterBank import myPemoAnalysisFilterBank
from .myPemoSynthesisFilterBank import myPemoSynthesisFilterBank

# >>> MATLAB
# function outputFilenames = extractDistortionComponents(...
#     srcFiles,estFile,options)
# % Decomposition of an estimated source (or source image) into
# %      the true target
# %      + the target distortion (spatially-distorted and filtered version
# %      of the target)
# %      + the interference distortion component (spatially-distorted and
# %      filtered version of other sources)
# %      + the artifact and noise component
# %
# % Usage:
# %
# %   - outputFilenames = extractDistortionComponents(srcFiles,estFile)
# % 
# %   - outputFilenames = extractDistortionComponents(srcFiles,estFile,options)
# %
# % Inputs:
# %   srcFiles is a cell array with the file names related to the
# %   true sources (the target source is the first one), estFile is a string.
# %   Signals must be stored in .wav files.
# %
# % Outputs:
# %   the file names of the resulting sounds are returned as a cell array in
# %   outputFilenames.
# %
# % Optional input:
# %      options.destDir (default: './'): output directory where distortion
# %       component .wav files are written.
# %      options.segmentationFactor (default: 1): the signals are splitted in
# %      options.segmentationFactor parts which are processed successively
# %       and finally merged with an overlap-add method. Increase this number
# %       when experiencing Out of Memory issues.
# %      options.frameLength (default: .5): frame length, in seconds, for the
# %       1kHz band, for the time vaying analysis. The frame length in
# %       other bands is derived from this parameter and is proportional to
# %       the bandwith.
# %      options.filterLength (default: .04): filter length, in seconds, for
# %       the 1kHz band, for the allowed filtering distortions. The filter
# %       length in other bands is derived from this parameter and is
# %       proportional to the bandwith.
# %      options.shadeInMs (default: 10): when nonnegative, this number is
# %       the length, in ms, of half a hanning window used to insert a shade
# %       in.
# %      options.shadeOutMs (default: 10) when nonnegative, this number is
# %       the length, in ms, of half a hanning window used to insert a shade
# %       out.
# %      options.tmpDir (default: system default temporary directory):
# %       directory where temporary files are written.
# %      options.outputFilenames (default: []): filenames of the distortion 
# %      components generated by the method.
# %      options.FLAG_2PROJ (default: false): boolean flag to use two
# %       least square projections (true) or only one (false).
# %
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# % Version history
# %  - Version 1.0.1, September 2011: added error in case sound files have
# %  different sizes
# %  - Version 1.0, June 2010: first release
# % Copyright 2010-2011 Valentin Emiya (INRIA).
# % This software is distributed under the terms of the GNU Public License
# % version 3 (http://www.gnu.org/licenses/gpl.txt).
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#
#
# <<< MATLAB


# !!! DEVIATION: the file I/O is inverted. MATLAB's entry point takes .wav
# filenames, reads them, and writes four .wav files; the callers this reference
# serves want arrays. The transcription below therefore takes the SIGNALS that
# MATLAB would have read (`srcSignals`, `estSignal`, plus their shared `fs`) and
# returns the four component arrays, with `estFile` retained purely as the name
# the output filenames are derived from. `extractDistortionComponents_files` at
# the bottom of this module restores MATLAB's exact signature on top of it. No
# numerical step is affected; only where bytes enter and leave.
def extractDistortionComponents(srcSignals, estSignal, fs,
                                options=None, estFile='estimate', verbose=False):
    """Decompose `estSignal` against `srcSignals` (the target source first).

    Each signal is an (nSamples, nChannels) float array in [-1, 1), as
    `audioread` would have returned. Returns
    `(trueSynth, targetSynth, interfSynth, artifSynth, outputFilenames)`.
    """
# >>> MATLAB
# if nargin<2
#     error('extractDistortionComponents:notEnoughArguments','Not enough arguments');
# end
#
# <<< MATLAB
    # `nargin<2` cannot happen: `estSignal` is a required positional parameter.

# >>> MATLAB
# defaultOptions.destDir = './';
# defaultOptions.tmpDir = tempdir;
# defaultOptions.outputFilenames = [];
# defaultOptions.GR = false;
# defaultOptions.FLAG_2PROJ = false;
# defaultOptions.frameLength = .5;
# defaultOptions.filterLength = .04;
# defaultOptions.segmentationFactor = 1;
# defaultOptions.shadeInMs = 10;
# defaultOptions.shadeOutMs = 10;
#
# if nargin<3
#     options = defaultOptions;
# else
#     names = fieldnames(defaultOptions);
#     for k=1:length(names)
#         if ~isfield(options,names{k}) || isempty(options.(names{k}))
#             options.(names{k}) = defaultOptions.(names{k});
#         end
#     end
# end
#
# <<< MATLAB
    defaultOptions = {
        'destDir': './',
        'tmpDir': tempfile.gettempdir(),
        'outputFilenames': None,  # MATLAB []
        'GR': False,
        'FLAG_2PROJ': False,
        'frameLength': .5,
        'filterLength': .04,
        'segmentationFactor': 1,
        'shadeInMs': 10,
        'shadeOutMs': 10,
    }

    if options is None:  # MATLAB nargin<3
        options = dict(defaultOptions)
    else:
        options = dict(options)  # MATLAB passes structs by value
        names = list(defaultOptions)  # MATLAB fieldnames(defaultOptions)
        for k in range(1, len(names) + 1):  # MATLAB k=1:length(names)
            name = names[k - 1]
            # MATLAB ~isfield(...) || isempty(...); `[]` maps to None/empty here
            if name not in options or options[name] is None or (
                    isinstance(options[name], (list, tuple)) and len(options[name]) == 0):
                options[name] = defaultOptions[name]

# >>> MATLAB
# destDir = options.destDir;
#
# J = length(srcFiles);
#
# <<< MATLAB
    destDir = options['destDir']

    J = len(srcSignals)  # MATLAB length(srcFiles)

# >>> MATLAB
# if isempty(options.outputFilenames)
#     outputFilenames = cell(4,1);
#     [dum filename] = fileparts(estFile);
#     outputFilenames{1} = [destDir filename '_true.wav'];
#     outputFilenames{2} = [destDir filename '_eTarget.wav'];
#     outputFilenames{3} = [destDir filename '_eInterf.wav'];
#     outputFilenames{4} = [destDir filename '_eArtif.wav'];
#     options.outputFilenames = outputFilenames;
# else
#     outputFilenames = options.outputFilenames;
# end
#
# <<< MATLAB
    if options['outputFilenames'] is None or len(options['outputFilenames']) == 0:
        outputFilenames = [None] * 4  # MATLAB cell(4,1)
        # MATLAB [dum filename] = fileparts(estFile): basename without extension
        filename = os.path.splitext(os.path.basename(estFile))[0]
        outputFilenames[0] = destDir + filename + '_true.wav'
        outputFilenames[1] = destDir + filename + '_eTarget.wav'
        outputFilenames[2] = destDir + filename + '_eInterf.wav'
        outputFilenames[3] = destDir + filename + '_eArtif.wav'
        options['outputFilenames'] = outputFilenames
    else:
        outputFilenames = options['outputFilenames']

# >>> MATLAB
# if options.segmentationFactor>1
#     aux_segmentAndDecompose(srcFiles,estFile,options);
#     return
# end
#
# <<< MATLAB
    if options['segmentationFactor'] > 1:
        aux_segmentAndDecompose(srcSignals, estSignal, options)
        return

# >>> MATLAB
# % Check that all sounds have the same format
# % RLB
# % siz = wavread(estFile,'size');
# infos_est = audioinfo(estFile);
# siz_est = [infos_est.TotalSamples infos_est.NumChannels];
# for j=1:J
#     % RLB
#     infos_src = audioinfo(srcFiles{j});
#     siz_src = [infos_src.TotalSamples infos_src.NumChannels];
#     if any(siz_est~=siz_src)
#         fprintf(2,'Size of source file %d (%s): %d x %d\n',...
#             j,srcFiles{j},siz_src);
#         fprintf(2,'Size of estimate file (%s): %d x %d\n',estFile,siz_est);
#         error('PEASS:BadSoundSize',...
#             'Sound files must have the same size (length and number of channels).');
#     end
# end
#
#
# <<< MATLAB
    # The signals are already in memory, so the "same format" check is a shape
    # comparison rather than an `audioinfo` one.
    estSignal = _as_audio_matrix(estSignal)
    siz_est = estSignal.shape
    for j in range(1, J + 1):  # MATLAB j=1:J
        siz_src = _as_audio_matrix(srcSignals[j - 1]).shape
        if siz_est != siz_src:
            print('Size of source file %d: %d x %d' % (j, siz_src[0], siz_src[1]),
                  file=sys.stderr)
            print('Size of estimate file: %d x %d' % (siz_est[0], siz_est[1]),
                  file=sys.stderr)
            raise ValueError(
                'PEASS:BadSoundSize '
                'Sound files must have the same size (length and number of channels).')

# >>> MATLAB
# fid = 1;
#
# fprintf(fid,'\n*********************************************\n');
# fprintf(fid,'Processing of:\n');
# fprintf(fid,' - %s\n',estFile);
# fprintf(fid,'*********************************************\n\n');
#
#
# <<< MATLAB
    if verbose:
        print('\n*********************************************')
        print('Processing of:')
        print(' - %s' % estFile)
        print('*********************************************\n')

# >>> MATLAB
# %% Auditory filter bank
# fprintf('Auditory filter bank... ');
# % RLB
# %siz = wavread(srcFiles{1},'size');
# %NChan = siz(2);
# infos_src = audioinfo(srcFiles{1});
# NChan = infos_src.NumChannels;
#
# <<< MATLAB
    if verbose:
        print('Auditory filter bank... ', end='')
    NChan = _as_audio_matrix(srcSignals[0]).shape[1]  # MATLAB infos_src.NumChannels

# >>> MATLAB
# sj_gamma = cell(J,NChan);
# Mmod = []; % to store coefficients and save computations
# for j=1:J
#     % RLB
#     [sj fs] = audioread(srcFiles{j});
#     if options.shadeInMs>0
#         wShadeIn = hann(2*round(options.shadeInMs/1000*fs+1),'periodic');
#         wShadeIn = wShadeIn(2:end/2);
#         for nChan = 1:NChan
#             sj(1:length(wShadeIn),nChan) = sj(1:length(wShadeIn),nChan).*wShadeIn;
#         end
#     end
#     if options.shadeOutMs>0
#         wShadeOut = hann(2*round(options.shadeOutMs/1000*fs+1),'periodic');
#         wShadeOut = wShadeOut(2:end/2);
#         wShadeOut = flipud(wShadeOut);
#         for nChan = 1:NChan
#             sj(size(sj,1)+(-length(wShadeOut)+1:0),nChan) = sj(size(sj,1)+(-length(wShadeOut)+1:0),nChan).*wShadeOut;
#         end
#     end
#     for nChan = 1:NChan
#         [sj_gamma{j,nChan}, analyzer, Mmod] =...
#             myPemoAnalysisFilterBank(sj(:,nChan),fs,Mmod);
#     end
# end
#
# <<< MATLAB
    sj_gamma = [[None] * NChan for _ in range(J)]  # MATLAB cell(J,NChan)
    Mmod = None  # to store coefficients and save computations
    for j in range(1, J + 1):  # MATLAB j=1:J
        # MATLAB's `sj` is a fresh copy from audioread and is then shaded in
        # place; copying keeps the caller's array unmodified.
        sj = _as_audio_matrix(srcSignals[j - 1]).copy()
        if options['shadeInMs'] > 0:
            # hann(2*round(...),'periodic') then (2:end/2): the rising half of a
            # periodic Hann, minus its leading zero. The length is always even,
            # so `end/2` is exact.
            wShadeIn = hann_periodic(2 * matlab_round(options['shadeInMs'] / 1000 * fs + 1))
            wShadeIn = wShadeIn[1:len(wShadeIn) // 2]  # MATLAB wShadeIn(2:end/2)
            for nChan in range(1, NChan + 1):  # MATLAB nChan=1:NChan
                sj[0:len(wShadeIn), nChan - 1] = sj[0:len(wShadeIn), nChan - 1] * wShadeIn
        if options['shadeOutMs'] > 0:
            wShadeOut = hann_periodic(2 * matlab_round(options['shadeOutMs'] / 1000 * fs + 1))
            wShadeOut = wShadeOut[1:len(wShadeOut) // 2]  # MATLAB wShadeOut(2:end/2)
            wShadeOut = np.flipud(wShadeOut)
            for nChan in range(1, NChan + 1):
                # MATLAB size(sj,1)+(-length(wShadeOut)+1:0) -> the final
                # length(wShadeOut) rows
                sj[-len(wShadeOut):, nChan - 1] = sj[-len(wShadeOut):, nChan - 1] * wShadeOut
        for nChan in range(1, NChan + 1):  # MATLAB nChan=1:NChan
            sj_gamma[j - 1][nChan - 1], analyzer, Mmod = \
                myPemoAnalysisFilterBank(sj[:, nChan - 1], fs, Mmod)

# >>> MATLAB
# sj_est_gamma = cell(1,NChan);
# [sj fs] = audioread(estFile);
# if options.shadeInMs>0
#     wShadeIn = hann(2*round(options.shadeInMs/1000*fs+1),'periodic');
#     wShadeIn = wShadeIn(2:end/2);
#     for nChan = 1:NChan
#         sj(1:length(wShadeIn),nChan) = sj(1:length(wShadeIn),nChan).*wShadeIn;
#     end
# end
# if options.shadeOutMs>0
#     wShadeOut = hann(2*round(options.shadeOutMs/1000*fs+1),'periodic');
#     wShadeOut = wShadeOut(2:end/2);
#     wShadeOut = flipud(wShadeOut);
#     for nChan = 1:NChan
#         sj(size(sj,1)+(-length(wShadeOut)+1:0),nChan) = sj(size(sj,1)+(-length(wShadeOut)+1:0),nChan).*wShadeOut;
#     end
# end
# for nChan = 1:NChan
#     [sj_est_gamma{1,nChan}, analyzer] =...
#         myPemoAnalysisFilterBank(sj(:,nChan),fs,Mmod);
# end
#
# Mmod = [];
#
# fprintf('Done\n')
#
# <<< MATLAB
    sj_est_gamma = [[None] * NChan]  # MATLAB cell(1,NChan)
    sj = _as_audio_matrix(estSignal).copy()
    if options['shadeInMs'] > 0:
        wShadeIn = hann_periodic(2 * matlab_round(options['shadeInMs'] / 1000 * fs + 1))
        wShadeIn = wShadeIn[1:len(wShadeIn) // 2]  # MATLAB wShadeIn(2:end/2)
        for nChan in range(1, NChan + 1):
            sj[0:len(wShadeIn), nChan - 1] = sj[0:len(wShadeIn), nChan - 1] * wShadeIn
    if options['shadeOutMs'] > 0:
        wShadeOut = hann_periodic(2 * matlab_round(options['shadeOutMs'] / 1000 * fs + 1))
        wShadeOut = wShadeOut[1:len(wShadeOut) // 2]  # MATLAB wShadeOut(2:end/2)
        wShadeOut = np.flipud(wShadeOut)
        for nChan in range(1, NChan + 1):
            sj[-len(wShadeOut):, nChan - 1] = sj[-len(wShadeOut):, nChan - 1] * wShadeOut
    for nChan in range(1, NChan + 1):  # MATLAB nChan=1:NChan
        sj_est_gamma[0][nChan - 1], analyzer, _ = \
            myPemoAnalysisFilterBank(sj[:, nChan - 1], fs, Mmod)

    Mmod = None  # MATLAB Mmod = []

    if verbose:
        print('Done')

# >>> MATLAB
# %% Bandwise component extraction
# fprintf('Bandwise component extraction... ');
#
# % format conversion
# s = cellA12_cellB_vecC_2_cellB_vecCA21(sj_gamma);
# sEst = cellA12_cellB_vecC_2_cellB_vecCA21(sj_est_gamma);
#
# clear sj_gamma sj_est_gamma
# fRef = 1000;
# TframeFRef = options.frameLength;
# ThopFRef = TframeFRef/4;
# [dum I] = min(abs(analyzer.center_frequencies_hz-fRef));
# bwRef = analyzer.bw(I);
# fsb = analyzer.fs./analyzer.Ndec;
# TfilterFRef = min(options.filterLength,TframeFRef/NChan/J/3);
# flens = max(3,...
#     2*round((TfilterFRef*bwRef./analyzer.bw.*fsb-1)/2)'+1); % longueur impaire filtres
# Lws = max(3,round(TframeFRef*bwRef./analyzer.bw.*fsb))'; % longueur trames
# hops = max(1,round(ThopFRef*bwRef./analyzer.bw.*fsb))';% hop sizes
#
# <<< MATLAB
    if verbose:
        print('Bandwise component extraction... ', end='')

    # format conversion
    s = cellA12_cellB_vecC_2_cellB_vecCA21(sj_gamma)
    sEst = cellA12_cellB_vecC_2_cellB_vecCA21(sj_est_gamma)

    del sj_gamma, sj_est_gamma  # MATLAB clear
    fRef = 1000
    TframeFRef = options['frameLength']
    ThopFRef = TframeFRef / 4
    center_frequencies_hz = np.asarray(mstruct_get(analyzer, 'center_frequencies_hz'))
    # MATLAB [dum I] = min(...): the index of the band nearest 1 kHz. `argmin`
    # matches MATLAB's first-minimum tie-break.
    I = int(np.argmin(np.abs(center_frequencies_hz - fRef)))
    bw = np.asarray(mstruct_get(analyzer, 'bw'))
    bwRef = bw[I]  # MATLAB analyzer.bw(I), 1-based -> argmin is already 0-based
    fsb = np.asarray(mstruct_get(analyzer, 'fs')) / np.asarray(mstruct_get(analyzer, 'Ndec'))
    TfilterFRef = min(options['filterLength'], TframeFRef / NChan / J / 3)
    # longueur impaire filtres -- odd by construction: 2*round(...)+1
    flens = np.maximum(3, 2 * matlab_round((TfilterFRef * bwRef / bw * fsb - 1) / 2) + 1)
    Lws = np.maximum(3, matlab_round(TframeFRef * bwRef / bw * fsb))  # longueur trames
    hops = np.maximum(1, matlab_round(ThopFRef * bwRef / bw * fsb))  # hop sizes

# >>> MATLAB
# sgTrue = cell(size(s));
# egTarget = cell(size(s));
# egInterf = cell(size(s));
# egArtif = cell(size(s));
# for k=1:length(s)
#     % In each band, decompose
#     [sgTrue{k},egTarget{k},egInterf{k},egArtif{k}] = ...
#         extractTSIA(s{k},sEst{k},flens(k),Lws(k),hops(k),...
#         options);
# end
# fprintf('Done\n')
#
# clear s sEst
#
# <<< MATLAB
    sgTrue = [None] * len(s)  # MATLAB cell(size(s))
    egTarget = [None] * len(s)
    egInterf = [None] * len(s)
    egArtif = [None] * len(s)
    for k in range(1, len(s) + 1):  # MATLAB k=1:length(s)
        # In each band, decompose
        sgTrue[k - 1], egTarget[k - 1], egInterf[k - 1], egArtif[k - 1] = \
            extractTSIA(s[k - 1], sEst[k - 1], int(flens[k - 1]), int(Lws[k - 1]),
                        int(hops[k - 1]), options)
    if verbose:
        print('Done')

    del s, sEst  # MATLAB clear

# >>> MATLAB
# % format conversion
# s_gamma_true = cellB_vecCA21_2_cellA12_cellB_vecC(sgTrue);
# s_gamma_target = cellB_vecCA21_2_cellA12_cellB_vecC(egTarget);
# s_gamma_interf = cellB_vecCA21_2_cellA12_cellB_vecC(egInterf);
# s_gamma_artif = cellB_vecCA21_2_cellA12_cellB_vecC(egArtif);
#
# clear sgTrue egTarget egInterf egArtif
#
# <<< MATLAB
    # format conversion
    s_gamma_true = cellB_vecCA21_2_cellA12_cellB_vecC(sgTrue)
    s_gamma_target = cellB_vecCA21_2_cellA12_cellB_vecC(egTarget)
    s_gamma_interf = cellB_vecCA21_2_cellA12_cellB_vecC(egInterf)
    s_gamma_artif = cellB_vecCA21_2_cellA12_cellB_vecC(egArtif)

    del sgTrue, egTarget, egInterf, egArtif  # MATLAB clear

# >>> MATLAB
# %% Component synthesis
# fprintf('Component synthesis... ');
# for nChan = 1:NChan
#     [trueSynth(:,nChan), synthesizer, Mmod] = ...
#         myPemoSynthesisFilterBank(s_gamma_true{1,nChan},analyzer,Mmod);
#     [targetSynth(:,nChan), synthesizer, Mmod] = ...
#         myPemoSynthesisFilterBank(s_gamma_target{1,nChan},analyzer,Mmod);
#     [interfSynth(:,nChan), synthesizer, Mmod] = ...
#         myPemoSynthesisFilterBank(s_gamma_interf{1,nChan},analyzer,Mmod);
#     [artifSynth(:,nChan), synthesizer, Mmod] = ...
#         myPemoSynthesisFilterBank(s_gamma_artif{1,nChan},analyzer,Mmod);
# end
# <<< MATLAB
    if verbose:
        print('Component synthesis... ', end='')
    # MATLAB grows `trueSynth(:,nChan)` column by column; collected and stacked
    # here instead, which is the same matrix.
    trueSynth, targetSynth, interfSynth, artifSynth = [], [], [], []
    for nChan in range(1, NChan + 1):  # MATLAB nChan=1:NChan
        column, synthesizer, Mmod = \
            myPemoSynthesisFilterBank(s_gamma_true[0][nChan - 1], analyzer, Mmod)
        trueSynth.append(column)
        column, synthesizer, Mmod = \
            myPemoSynthesisFilterBank(s_gamma_target[0][nChan - 1], analyzer, Mmod)
        targetSynth.append(column)
        column, synthesizer, Mmod = \
            myPemoSynthesisFilterBank(s_gamma_interf[0][nChan - 1], analyzer, Mmod)
        interfSynth.append(column)
        column, synthesizer, Mmod = \
            myPemoSynthesisFilterBank(s_gamma_artif[0][nChan - 1], analyzer, Mmod)
        artifSynth.append(column)
    trueSynth = np.column_stack(trueSynth)
    targetSynth = np.column_stack(targetSynth)
    interfSynth = np.column_stack(interfSynth)
    artifSynth = np.column_stack(artifSynth)

# >>> MATLAB
# % RLB
# %wavwrite(trueSynth,fs,outputFilenames{1,1});
# %wavwrite(targetSynth,fs,outputFilenames{2,1});
# %wavwrite(interfSynth,fs,outputFilenames{3,1});
# %wavwrite(artifSynth,fs,outputFilenames{4,1});
# audiowrite(outputFilenames{1,1},trueSynth,fs);
# audiowrite(outputFilenames{2,1},targetSynth,fs);
# audiowrite(outputFilenames{3,1},interfSynth,fs);
# audiowrite(outputFilenames{4,1},artifSynth,fs);
#
# clear trueSynth targetSynth interfSynth artifSynth
# fprintf('Done\n')
#
#
# return
#
# <<< MATLAB
    # The four `audiowrite` calls live in `extractDistortionComponents_files`;
    # here the arrays themselves are the result (see the DEVIATION at the top).
    if verbose:
        print('Done')

    return trueSynth, targetSynth, interfSynth, artifSynth, outputFilenames


# >>> MATLAB
# %%%%%%%%%%%%%%%%%
# function aux_segmentAndDecompose(srcFiles,estFile,options)
# try
#     % RLB
#     %[siz fs] = wavread(srcFiles{1},'size');
#     infos_src = audioinfo(srcFiles{1});
#     siz = infos_src.TotalSamples;
#     fs = infos_src.SampleRate;
#     
#     TCut = ceil(siz(1)/options.segmentationFactor)/fs;
#     for kj=1:length(srcFiles)
#         [originalCutFiles(:,kj)] = aux_cutWav(srcFiles{kj},TCut);
#     end
#     optionsCut = options;
#     optionsCut.segmentationFactor = 1;
#     optionsCut.outputFilenames = [];
#     optionsCut.destDir = tempdir;
#     [estimateCutFiles,Istart] = aux_cutWav(estFile,TCut);
#     for kCut = 1:length(estimateCutFiles)
#         optionsCut.shadeInMs = 0;
#         optionsCut.shadeOutMs = 0;
#         if kCut==1
#             optionsCut.shadeInMs = 10;
#         end
#         if kCut==length(estimateCutFiles)
#             optionsCut.shadeOutMs = 10;
#         end
#         TSIANamesCut{kCut} = extractDistortionComponents(...
#             originalCutFiles(kCut,:),estimateCutFiles{kCut},optionsCut);
#     end
#     aux_mergeWav(estimateCutFiles,estFile,Istart,options);
#     for k=1:length(estimateCutFiles(:))
#         delete(estimateCutFiles{k});
#     end
#     %     end
# catch %ME
#     for k=1:length(originalCutFiles(:))
#         delete(originalCutFiles{k});
#     end
#     for k=1:length(estimateCutFiles(:))
#         delete(estimateCutFiles{k});
#     end
#     rethrow(lasterror);%(ME);
# end
# for k=1:length(originalCutFiles(:))
#     delete(originalCutFiles{k});
# end
#
# return
#
# <<< MATLAB


# !!! DEVIATION: `aux_segmentAndDecompose` and its helpers are not implemented.
# The shipped v2.0.1 code path is broken: `aux_mergeWav` sets
# `siz0 = infos_est.TotalSamples`, a SCALAR (the pre-`audioinfo` `wavread` it
# replaced returned `[nSamples nChannels]`), so `zeros(siz0)` allocates a
# siz0-by-siz0 matrix and `siz0(2)` on the next lines indexes out of bounds.
# It therefore cannot run in MATLAB either, and transcribing it would produce
# Python that is faithful only to code that does not work. Raising is the
# honest behaviour; the MATLAB is still embedded above and below, verbatim, so
# the transcription check covers it.
def aux_segmentAndDecompose(srcFiles, estFile, options):
    raise NotImplementedError(
        "segmentationFactor > 1 is not supported: the MATLAB v2.0.1 "
        "aux_mergeWav path is itself broken (see the DEVIATION note above)."
    )


# >>> MATLAB
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# function [filenames,Istart] = aux_cutWav(file,T)
# % RLB
# %[siz,fs] = wavread(file,'size');
# infos_file = audioinfo(file);
# siz = infos_file.TotalSamples;
# fs = infos_file.SampleRate;
#     
# N = 2*round(T*fs/2);
# Istart = 1:N/2:siz(1)-N/2+1;
# Iend = min(Istart+N-1,siz(1));
#
# destBase = tempname;
# for kCut = 1:length(Istart)
#     % RLB
#     %[x,fs] = wavread(file,[Istart(kCut), Iend(kCut)]);
#     %wavwrite(x,fs,[destBase '_' num2str(kCut) '.wav']);
#     [x,fs] = audioread(file,[Istart(kCut), Iend(kCut)]);
#     audiowrite([destBase '_' num2str(kCut) '.wav'],x,fs);
#    
#     filenames{kCut} = [destBase '_' num2str(kCut) '.wav'];
# end
# return
# <<< MATLAB


def aux_cutWav(file, T):
    raise NotImplementedError("only reached from aux_segmentAndDecompose")


# >>> MATLAB
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# function aux_mergeWav(cutFilenames,estFile,Istart,options)
# % RLB
# %[siz0 fs] = wavread(estFile,'size');
# infos_est = audioinfo(estFile);
# siz0 = infos_est.TotalSamples;
# fs = infos_est.SampleRate;
#
# components = {'true','eArtif','eTarget','eInterf'};
#
# for kComp = 1:length(components)
#     x = zeros(siz0);
#     w = zeros(siz0);
#     for kCut = 1:length(Istart)
#         sourceFile = [cutFilenames{kCut}(1:end-4) '_' components{kComp} '.wav'];
#         % RLB
#         %xCut = wavread(sourceFile);
#         xCut = audioread(sourceFile);
#         if kComp==1 && kCut==1
#             wCut = flipud(hann(size(xCut,1),'periodic'))*ones(1,siz0(2));
#         end
#         N = size(xCut,1);
#         if Istart(kCut)+N-1>size(x,1)
#             xCut = xCut(1:size(x,1)-Istart(kCut)+1,:);
#             N = size(xCut,1);
#         end
#         x(Istart(kCut)+(0:N-1),:) = x(Istart(kCut)+(0:N-1),:) ...
#             + xCut.*wCut(1:N,:);
#         w(Istart(kCut)+(0:N-1),:) = w(Istart(kCut)+(0:N-1),:) ...
#             + wCut(1:N,:);
#     end
#     I = w(:)~=0;
#     x(I) = x(I)./w(I);
#     
#     [dum destFilename] = fileparts(estFile);
#     destFilename = sprintf(...
#         '%s%s_%s.wav',...
#         options.destDir,destFilename,components{kComp});
#     % RLB
#     %wavwrite(x,fs,destFilename);
#     audiowrite(destFilename,x,fs);
# end
#
#
# return
#
# <<< MATLAB


def aux_mergeWav(cutFilenames, estFile, Istart, options):
    raise NotImplementedError("only reached from aux_segmentAndDecompose")


# >>> MATLAB
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# function y = cellA12_cellB_vecC_2_cellB_vecCA21(x)
# % format conversion
#
# [A1 A2] = size(x);
# [B1 B2]= size(x{1,1});
# C = cellfun('length',x{1,1});
#
# y = arrayfun(@(n)zeros(n,A2,A1),C,'UniformOutput',false);
# for a1=1:A1
#     for a2=1:A2
#         for b1=1:B1
#             for b2=1:B2
#                 y{b1,b2}(:,a2,a1) = x{a1,a2}{b1,b2};
#             end
#         end
#     end
# end
#
# return
#
# <<< MATLAB


def cellA12_cellB_vecC_2_cellB_vecCA21(x):
    # format conversion
    # x is an A1-by-A2 list of lists, each entry a B1-long list of 1-D subband
    # vectors (MATLAB's cell{a1,a2}{b1,b2}). MATLAB's second cell dimension B2
    # is always 1 here, so it is dropped rather than carried as a length-1 axis.
    A1 = len(x)
    A2 = len(x[0])
    B1 = len(x[0][0])  # MATLAB [B1 B2] = size(x{1,1}), B2 == 1
    C = [len(v) for v in x[0][0]]  # MATLAB cellfun('length',x{1,1})

    dtype = np.asarray(x[0][0][0]).dtype
    # MATLAB arrayfun(@(n)zeros(n,A2,A1),C,...)
    y = [np.zeros((n, A2, A1), dtype=dtype) for n in C]
    for a1 in range(1, A1 + 1):  # MATLAB a1=1:A1
        for a2 in range(1, A2 + 1):  # MATLAB a2=1:A2
            for b1 in range(1, B1 + 1):  # MATLAB b1=1:B1
                # MATLAB y{b1,b2}(:,a2,a1) = x{a1,a2}{b1,b2}
                y[b1 - 1][:, a2 - 1, a1 - 1] = np.asarray(x[a1 - 1][a2 - 1][b1 - 1])

    return y


# >>> MATLAB
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# function x = cellB_vecCA21_2_cellA12_cellB_vecC(y)
# % format conversion
#
# [B1 B2]= size(y);
# [dum A2 A1] = size(y{1,1});
#
# x = cell(A1,A2);
# for a1=1:A1
#     for a2=1:A2
#         x{a1,a2} = cell(B1,B2);
#         for b1=1:B1
#             for b2=1:B2
#                 x{a1,a2}{b1,b2} = squeeze(y{b1,b2}(:,a2,a1)).';
#             end
#         end
#     end
# end
#
# return
#
# <<< MATLAB


def cellB_vecCA21_2_cellA12_cellB_vecC(y):
    # format conversion
    B1 = len(y)  # MATLAB [B1 B2] = size(y), B2 == 1
    # MATLAB [dum A2 A1] = size(y{1,1}): with NEst == 1 MATLAB drops the
    # trailing singleton and fills A1 with 1, which is what shape[2] gives here.
    A2 = y[0].shape[1]
    A1 = y[0].shape[2]

    x = [[None] * A2 for _ in range(A1)]  # MATLAB cell(A1,A2)
    for a1 in range(1, A1 + 1):  # MATLAB a1=1:A1
        for a2 in range(1, A2 + 1):  # MATLAB a2=1:A2
            x[a1 - 1][a2 - 1] = [None] * B1  # MATLAB cell(B1,B2)
            for b1 in range(1, B1 + 1):  # MATLAB b1=1:B1
                # MATLAB squeeze(y{b1,b2}(:,a2,a1)).' -> a row vector
                x[a1 - 1][a2 - 1][b1 - 1] = y[b1 - 1][:, a2 - 1, a1 - 1]

    return x


# ---------------------------------------------------------------------------
# File-level wrapper restoring MATLAB's own signature. Not part of the
# transcription proper; see the DEVIATION on `extractDistortionComponents`.
# ---------------------------------------------------------------------------

def _as_audio_matrix(signal):
    """`audioread` always returns nSamples-by-nChannels, even for mono."""
    a = np.asarray(signal, dtype=float)
    if a.ndim == 1:
        return a.reshape(-1, 1)
    return a


def audioread(filename):
    """MATLAB `[y, fs] = audioread(file)` for PCM-16 wav files.

    MATLAB normalizes 16-bit integer samples by 32768 onto [-1, 1).
    """
    fs, data = scipy.io.wavfile.read(filename)
    if data.dtype == np.int16:
        data = data.astype(float) / 32768.0
    else:
        data = data.astype(float)
    return _as_audio_matrix(data), float(fs)


# !!! DEVIATION: MATLAB's exact float-to-int16 rule for `audiowrite` is not
# documented and could not be verified here, so `round(y*32768)` clipped to the
# int16 range is used -- the convention the older `wavwrite` used. Any
# disagreement is at most one LSB (~3e-5 of full scale), and it affects only
# this file wrapper: the array API, which is what the tests and every caller
# use, never quantizes at all.
def audiowrite(filename, y, fs):
    """MATLAB `audiowrite(file, y, fs)`, 16-bit PCM."""
    scaled = np.clip(matlab_round(np.asarray(y) * 32768.0), -32768, 32767)
    scipy.io.wavfile.write(filename, int(fs), scaled.astype(np.int16))


def extractDistortionComponents_files(srcFiles, estFile, options=None, verbose=False):
    """MATLAB's own entry point: filenames in, filenames out."""
    srcSignals = []
    fs = None
    for srcFile in srcFiles:
        signal, fs = audioread(srcFile)
        srcSignals.append(signal)
    estSignal, fs = audioread(estFile)

    trueSynth, targetSynth, interfSynth, artifSynth, outputFilenames = \
        extractDistortionComponents(srcSignals, estSignal, fs, options,
                                    estFile=estFile, verbose=verbose)

    audiowrite(outputFilenames[0], trueSynth, fs)
    audiowrite(outputFilenames[1], targetSynth, fs)
    audiowrite(outputFilenames[2], interfSynth, fs)
    audiowrite(outputFilenames[3], artifSynth, fs)
    return outputFilenames
