"""
PEASS Test Suite - Legacy Matlab Regression Tests
File path: tests/regression/test_matlab_regression.py
"""

import numpy as np
import pytest
import soundfile as sf

from peass import decompose_distortion_components
from peass.config import DecompositionConfiguration
from tests.conftest import to_backend_format
from tests.conftest import to_numpy_format


@pytest.mark.regression
def test_regression_against_matlab_references(matlab_ref_resources, peass_backend):
    """
    Validates BOTH Numpy and PyTorch backends directly against original
    reference WAV files generated by the official MATLAB PEASS v2.0.1 toolbox.
    """
    backend_type, device = peass_backend

    # 1. Load Inputs
    target_src, fs = sf.read(matlab_ref_resources / "targetSrc.wav")
    interf1, _ = sf.read(matlab_ref_resources / "interfSrc1.wav")
    interf2, _ = sf.read(matlab_ref_resources / "interfSrc2.wav")
    estimate, _ = sf.read(matlab_ref_resources / "targetEstimate.wav")

    # 2. Convert to targeted backend structures
    target_in = to_backend_format(target_src, backend_type, device)
    interf1_in = to_backend_format(interf1, backend_type, device)
    interf2_in = to_backend_format(interf2, backend_type, device)
    estimate_in = to_backend_format(estimate, backend_type, device)

    # 3. Execute decomposition
    config = DecompositionConfiguration(shade_in_milliseconds=10.0, shade_out_milliseconds=10.0)
    result = decompose_distortion_components(
        source_files=[target_in, interf1_in, interf2_in],
        estimate_file=estimate_in,
        configuration=config,
        sampling_frequency_hz=float(fs)
    )
    py_waveforms = result.waveforms

    # 3. Define components to verify against MATLAB gold standard files
    validation_map = [
        (to_numpy_format(py_waveforms.true_target), "targetEstimate_true.wav", "true_target"),
        (to_numpy_format(py_waveforms.target_distortion), "targetEstimate_eTarget.wav", "target_distortion"),
        (to_numpy_format(py_waveforms.interference), "targetEstimate_eInterf.wav", "interference"),
        (to_numpy_format(py_waveforms.artifacts), "targetEstimate_eArtif.wav", "artifacts")
    ]

    for py_val, gold_filename, label in validation_map:
        gold_val, _ = sf.read(matlab_ref_resources / gold_filename)

        # Sync lengths (handling decimation alignment limits)
        min_len = min(len(py_val), len(gold_val))
        py_segment = py_val[:min_len]
        gold_segment = gold_val[:min_len]

        for ch in range(py_segment.shape[1]):
            # If the segment is silent, correlation is NaN; check variance instead
            if np.std(gold_segment[:, ch]) < 1e-4:
                assert np.std(py_segment[:, ch]) < 1e-4, f"Energy mismatch in {label} channel {ch}"
            else:
                corr = np.corrcoef(py_segment[:, ch], gold_segment[:, ch])[0, 1]
                assert corr > 0.95, f"Regression failure on {backend_type} (device: {device}): {label} (CH{ch}) correlation is {corr:.4f}"
