name: Main

on:
  push:
    branches: [ "main" ]

# Cancel any active, outdated runs on the same branch
concurrency:
  group: main-test-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  post-merge-check:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.14" ]
        remove-numba: [ true, false ]

    uses: ./.github/workflows/template-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      remove-numba: ${{ matrix.remove-numba }}