name: Pull Request Tests

on:
  pull_request:
    branches: [ "main" ]

# Automatically cancels the active branch push test in favor of the PR test
concurrency:
  group: peass-test-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  validate:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13", "3.14" ]
        include:
          - os: windows-latest
            python-version: [ "3.9", "3.13" ]

    uses: ./.github/workflows/template-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}